### ISSUE TITLE
website link should be -> https://ropensci.github.io/gittargets/

### ISSUE THREAD

**Issue by ginolhac** [ropensci/gittargets#10]
Thanks for this first release!
A short issue is that the link on GitHub still points to `wlandau` and not `ropensci`.
Keep up the impressive work William ;)

**Comment by wlandau** [comment]
Thanks Aurélien! Just working through some minor permissions issues before I can change the URL: https://github.com/ropensci/software-review/issues/486#issuecomment-1011139556.

**Comment by wlandau** [comment]
Fixed.
