### ISSUE TITLE
`system2()` call "git" leads to issue on Windows

### ISSUE THREAD

**Issue by psychelzh** [ropensci/gittargets#12]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/gittargets/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is a genuine bug in the `gittargets` package itself and not a user error, known limitation, or issue from another package that `gittargets` depends on. For example, if you get errors running `tar_make_clustermq()`, try isolating the problem in a reproducible example that runs `clustermq` and not `gittargets`. And for miscellaneous troubleshooting, please post to [discussions](https://github.com/ropensci/gittargets/discussions) instead of [issues](https://github.com/ropensci/gittargets/issues).
* [x] If there is [already a relevant issue](https://github.com/ropensci/gittargets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

This is just the same as https://github.com/yihui/crandalf/issues/24. On Windows OS, `tar_git_ok()` complains even if the user name   and email are configured globally. This is simply because R for Windows sets `HOME` environment as Documents folder. Hopefully this is taken care of here.
 
## Reproducible example

``` r
gittargets::tar_git_ok()
#> ✔ Git binary: 'C:\PROGRA~1\Git\cmd\git.exe'
#> ✖ No Git config global user email. See details in ?tar_git_ok().
#> ✖ No Git config global user email. See details in ?tar_git_ok().
#> [1] FALSE
```

<sup>Created on 2022-08-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by psychelzh** [comment]
Maybe an alternative is to use "gert" package?

**Comment by wlandau** [comment]
Thanks for letting me know. Not sure why I forgot to use `processx::run()` on `gittargets:::tar_git_binary()` instead of `system2("git", ...)`, but the latest commits should fix it.

Unfortunately I can't use `gert` because `libgit2` is incompatible with Git LFS.

**Comment by wlandau** [comment]
Seems I misread the [docs of `processx::run()`](https://github.com/r-lib/processx/blob/84301784382296217e7f5d11e1116dc4e24da809/R/run.R#L110-L112). Look like we'll need to temporarily set `HOME` after all.

**Comment by wlandau** [comment]
Looks to be fixed this time: https://github.com/ropensci/gittargets/runs/7939003978
